# Generated by Django 2.0 on 2022-10-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('no', models.AutoField(db_column='no', primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='category', max_length=255)),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('summary', models.TextField(db_column='summary')),
                ('subject', models.CharField(db_column='subject', max_length=255)),
                ('contents', models.TextField(db_column='contents')),
                ('org_file_name', models.CharField(db_column='org_file_name', max_length=500)),
                ('file_name', models.CharField(db_column='file_name', max_length=500)),
                ('file_location', models.CharField(db_column='file_location', max_length=500)),
                ('createdate', models.DateTimeField(auto_now_add=True, db_column='createdate')),
                ('updatedate', models.DateTimeField(auto_now=True, db_column='updatedate')),
            ],
            options={
                'db_table': 'shop',
                'managed': True,
            },
        ),
    ]
